name: Build and Test Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker image
        run: docker-compose -f myOnlineShopPage/docker-compose.yml build

      - name: Start containers
        run: docker-compose -f myOnlineShopPage/docker-compose.yml up -d

      - name: Wait for web service to be ready
        run: |
          echo "Waiting for the web service to be ready..."
          sleep 10  # Даем немного времени контейнеру

      - name: Run tests
        run: |
          docker-compose -f myOnlineShopPage/docker-compose.yml exec -T web python manage.py test

      - name: Stop containers
        run: docker-compose -f myOnlineShopPage/docker-compose.yml down
